### ISSUE TITLE
Missing cancel button when initiating a trade.

### ISSUE THREAD

**Issue by thanksmister** [thanksmister/Local-Trader-Android#2]
There appears no cancel button when initiating a trade.   Only local trades that have not been funded can be canceled.  A user is reporting that there is no cancel button but has yet to produce any verification of the issue.  At this point this the issue is for investigation and verification.

**Comment by jac1013** [comment]
Hey guys, sorry that I didn't report this through here directly (you are right, this is the correct place). So the steps to reproduce are:

1 - I search for buying through Moneygram in any country.
2 - I get a list of users selling through Moneygram.
3 - I choose one of the users and initiate the trade with them.
4 - At this point no cancel button is available elsewhere in the app.
5 - After going through the "I paid" button there isn't a cancel button either.

OS: Android.
Phone: Samsung S8.

Expected Results: Possibility to cancel if I'm the one who initiated the trade just as we do in localbitcoins.com.

I'm pretty sure there wasn't a cancel button for my case because I had a problem in one of my trading because I guy wanted me to cancel but I couldn't because I wasn't in my PC.

Again, Many thanks for the great app.

**Comment by thanksmister** [comment]
First, I don't work for LocalBitcoins. I am just a developer who made the application and shared with others.  The application uses the LocalBitcoins API.  The only type of trades you can cancel are local trades, not online trades.  Moneygram is an online trade, and you can cancel only if you initiated it and only if its not funded.   I think since you when you initiate the trade and its already automatically funded, it's up to the seller to cancel it or you wait for the trade window to close.  

So you are expecting an cancel button when there would be no option to cancel the trade.  It may also be the case that the trade is disputed, which also can not be canceled.  If you have any doubts, you can login into the LocalBitcoins webpage and look at the trade to see if there is an option to cancel or dispute it.

**Comment by jac1013** [comment]
Ok, gotcha, well that specific case of the steps I described I was able to cancel through local bitcoins website. I just consider that this option should be available through the app because it will make it even more useful. It's just a suggestion. I'm not demanding anything here.

As for the only cancelling local trades I'm not so sure, in the past I cancelled 2 or 3 transactions in which I was the initiator and they were all online trades. I've never cancel through the app, only through their website tho.

EDIT: even though the trade I was trying to cancel was funded (physically) I forgot to fund it through the button, meaning that the cancel button should've been there for that case according to the instructions you provided, in any case, thanks for your time.

**Comment by thanksmister** [comment]
The application looks specifically for a cancel option in the data. If it’s there, a cancel button is shown.  I can’t do every trade test though because LocalBitcoins does not offer a developer account.  So I would have to trade for real just to test it.   But I can double check my logic.

**Comment by jac1013** [comment]
Make sense, I'll double check whenever I do a trade and let you know, if the button is there this issue is irrelevant. I'll report back in this issue when that happens.

**Comment by thanksmister** [comment]
That would be super helpful. If you find a particular case where there is a cancel button in the LBC site and not the app, let me know.

**Comment by jac1013** [comment]
Hey! So I have a case I can share with you, yesterday I was trying to make a transaction (which I initiated) and I couldn't because the other user didn't answer so I proceed to cancel it (I couldn't through the app, I'm not sure if I'm missing that cancel button or what) I did so through the website.

![image](https://user-images.githubusercontent.com/5025920/48135367-c12a8480-e26a-11e8-94b0-af054bd60577.png)

![image](https://user-images.githubusercontent.com/5025920/48135400-d4d5eb00-e26a-11e8-9eeb-3363d8afa04e.png)

![image](https://user-images.githubusercontent.com/5025920/48135424-ea4b1500-e26a-11e8-8752-f23ef6653f74.png)

These are screenshots of all the views I could access to... no cancel button in any of them.

Now this is the LCB website:

![image](https://user-images.githubusercontent.com/5025920/48135645-8248fe80-e26b-11e8-9375-c8513fadb833.png)

![image](https://user-images.githubusercontent.com/5025920/48135721-b58b8d80-e26b-11e8-82d0-e7284cc1e37b.png)

This is an online transaction and I was able to cancel it through LCB website, sorry that in my PC screenshots I didn't catch the transaction ID so you could see that they are the same, if you need this I can provide it to you later, but trust me, they are the same transaction.

Let me know your thoughts on this!

**Comment by thanksmister** [comment]
Ok, so I looked into the LBC rules for canceling a trade. You can cancel a trade if you are the buye. I am not sure what happens if you are the buyer and the trade has been marked paid or is being disputed.  I am not sure you can cancel in those contexts because each case needs to be test.   So I will just show the cancel button in those cases and what will happen if you try to cancel is an error will be returned if you can't cancel.  

So the logic in the application seems broken in that context due to the complexity of the cancel rules.   I am attempting to update the rules now to see if I can get this to work appropriately and will issue a new release which you may test.   Thanks for the feedback!!

**Comment by jac1013** [comment]
I'm happy to hear that, I'll surely be testing this pretty soon, I happen to cancel a lot of transactions because people don't answer. 

Anyway, I don't know what will happen after a dispute, for sure the cancel button works just after the buyer initiates the transaction, I've done that multiple times. I also had done it after marking the transaction as paid (it works too) but in the middle of a dispute I haven't, so your solution should work correctly for at least the 2 cases I mentioned, for dispute I'm not sure.

Thanks YOU for the implementation!

**Comment by thanksmister** [comment]
I have issued a new release in the beta channel on Google Play.  You may download the beta application for test from this link: https://play.google.com/apps/testing/com.thanksmister.bitcoin.localtrader.

**Comment by jac1013** [comment]
Hey @thanksmister cancel button is there in the options now, however, It seems like I'll successfully complete this one so I won't be able to test the cancel functionality per se, if you want we can keep this ticket open until I successfully cancel a transation through the app.

The button is also there after marking the transaction as paid.

Thanks for this, I'm changing my review in Google Play :).

**Comment by thanksmister** [comment]
Yes, let's keep this ticket open until we have validation.  Thanks for your help on this!
